version: '3.8'

services:
  web:
    image: pokemon-kd.com:latest
    container_name: pokemon-kd.com
    ports:
      - "3000:3000"
    networks:
      - pokemon
  nginx:
    image: nginx:latest 
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/pokemon-kingdom.com.conf
    - ./openssl:/etc/openssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pokemon

networks:
  pokemon:
    driver: bridge

  